name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
    - name: Docker Build and Push
      uses: ocker/build-push-action@v6.9.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          vtolao/kube-news:v1
          vtolao/kube-news:latest
