name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
    - name: Docker Build and Push
      uses: docker/build-push-action@v6.9.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          vtolao/kube-news:${{github.run_number}}
          vtolao/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Definindo o Context
      uses: azure/k8s-set-context@v4
      with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
  
